services:
  postgresdb:
    container_name: postgresdb
    environment:
      - POSTGRES_PASSWORD=passw0rd!
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgresdb_data:/var/lib/postgresql/data
  mysqldb:
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=passw0rd!
      - MYSQL_DATABASE=root
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysqldb_data:/var/lib/mysql

  elasticsearch:
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      # Tăng giới hạn file để không bị lỗi khi mở nhiều Segments
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200

   #microservices api section
  product-event-ingestor:
    container_name: product_ingestor_app
    ports:
      - "3000:3000"
    volumes:
      # Mount thư mục của service vào /app trong container
      - ./src/Services/ProductEventIngestor:/app
      # Giữ lại node_modules trong container, không bị ghi đè bởi máy host
      - /app/node_modules
    environment:
      NODE_ENV: ${NODE_ENV}
      # You can also set a default value if the variable is not found
      ES_NODE: http://elasticsearch:9200
      ES_INDEX: products
      PORT: 3000
    depends_on:
      - elasticsearch

  kibana:
    container_name: bonbon-kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_RETRY_DELAY=5000
    depends_on:
      - elasticsearch