apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: app-user
  namespace: kafka
  labels:
    strimzi.io/cluster: my-kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      # Read/Write topic test
      - resource:
          type: topic
          name: test
          patternType: literal
        operations:
          - Read
          - Write

      # Consumer group
      - resource:
          type: group
          name: app-group
          patternType: literal
        operations:
          - Read
