# Sử dụng phiên bản Node.js ổn định
FROM node:20-alpine

# Thiết lập thư mục làm việc bên trong container
WORKDIR /app

# Copy các file quản lý thư viện vào trước (dùng đường dẫn tương đối từ vị trí Dockerfile)
COPY package*.json ./

# Cài đặt thư viện
RUN npm install

# Copy toàn bộ mã nguồn của service này vào container
COPY . .

# Port mà service chạy
EXPOSE 3000

# Chạy lệnh dev (đã cấu hình nodemon trong package.json)
CMD ["npm", "run", "dev"]